# Generated by Django 6.0 on 2026-01-03 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_claim_claimant_alter_claim_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='posted_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
